# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_blog', '0004_blog_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='rated_users_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_user', models.CharField(max_length=100)),
            ],
        ),
    ]
